**1) Trabalhar com NumPy**

* Importar numpy e usar um alias para poder utilizar os seus recursos 

In [1]:
# Completar o exercício aqui
import numpy as np

* Criar um array de elementos (de 10 a 100)

In [3]:
lista_de_10_100 = np.arange(10,101)
print(f"Lista de 10 a 100: \n{lista_de_10_100}")
print("-"*70)

Lista de 10 a 100: 
[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]
----------------------------------------------------------------------


* Criar um array 3x3 com valores de 0 a 8 

In [4]:
array_0_a_8 = np.arange(9).reshape(3,3)
print(array_0_a_8)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


* Criar um array com valores aleatórios com o formato 3x3x3

In [5]:
array_valores_aleatorios_3x3x3 = np.random.randint(0,100,(3,3,3))
print(array_valores_aleatorios_3x3x3)

[[[34 43 42]
  [54 23 86]
  [52 40 32]]

 [[13 49  3]
  [23 92 61]
  [99 30  9]]

 [[51 31 32]
  [58 66  9]
  [41 81 77]]]


* Criar dois arrays, com valores aleatórios, A e B, e verificar se são iguais (há várias opções, investigar)

In [15]:
# Completar o exercício aqui
import numpy as np
A = np.random.randint(10,20, (5,3))
B = np.random.randint(0,10, (3,3))

# Verificar o tamanho dos arrays, pois se fizermos a comparação entre dois arrays de tamanho
# diferente pode  dar erro 
print(f" Listas originais ")
print(A)
print(B)
print("-"*50)
# Metodo 1: Usando np.array_equal()
# Metodo 2: np.array_equal()
arrai_igual = np.array_equal(A,B)
print(f"Verificando se os arrays são igual utilizando o np.array_equal() : {arrai_igual}")

# Metodo 2: np.array_equal()
# metodo 3 : Usando np.array_equiv()
# metodo 4 : Usando numpy.all com numpy.equal

""" if A.shape != B.shape:
    print(f"Os arrays não tem o mesmo tamanho {A.shape} e {B.shape}")

    # ajustando
    B = np.resize(B, A.shape)
    print("Depois da parear")
    print(A)
    print(B)
else:
    print("Os arrays têm a mesma forma.") """





 Listas originais 
[[13 13 13]
 [13 12 10]
 [10 16 16]
 [13 12 16]
 [15 13 11]]
[[0 3 5]
 [2 4 1]
 [4 8 4]]
--------------------------------------------------
Verificando se os arrays são igual utilizando o np.array_equal() : False


' if A.shape != B.shape:\n    print(f"Os arrays não tem o mesmo tamanho {A.shape} e {B.shape}")\n\n    # ajustando\n    B = np.resize(B, A.shape)\n    print("Depois da parear")\n    print(A)\n    print(B)\nelse:\n    print("Os arrays têm a mesma forma.") '

**2) Seguir com NumPy**

* Criar um array de 100 elementos aleatórios compreendidos entre 1 e 1000 (podem ser números inteiros).

In [19]:
import numpy as np

dolares = np.random.randint(1,1001, size= 100) # num aleatorios de 1 a 1000, com tamanho d 100

print(f"Lista de valores em dolares: {dolares}")

# a taxa de converção de USD para EUR
taxa_conversoa = 0.874413

# Fazer a conversão dos preços de dolares para euros 
euros = dolares * taxa_conversoa
euros = np.round(euros,2) # Duas casas decimais
print("--"* 50)

print(f"Valores em Euros {euros}")



Lista de valores em dolares: [268  90 212 939 348 293 249  74 958 543 851 330 940  31 603 876 879 257
 388 736 329 854 126 876 534 309 164 318 878  30 971  39 256 515 175 492
 166 976 308 334 375 291 307 552 686 806 236 785 393 487 738 776 315  27
 803 409 403 372 541 556  31 333 289  86  79 221 455 576 213  92 475 812
 723 911 402 975 161 371 188 510 252 691 275 195 693 141 477 336 108 269
  37  11 913 890 732 204 881  54 332 585]
----------------------------------------------------------------------------------------------------
Valores em Euros [234.34  78.7  185.38 821.07 304.3  256.2  217.73  64.71 837.69 474.81
 744.13 288.56 821.95  27.11 527.27 765.99 768.61 224.72 339.27 643.57
 287.68 746.75 110.18 765.99 466.94 270.19 143.4  278.06 767.73  26.23
 849.06  34.1  223.85 450.32 153.02 430.21 145.15 853.43 269.32 292.05
 327.9  254.45 268.44 482.68 599.85 704.78 206.36 686.41 343.64 425.84
 645.32 678.54 275.44  23.61 702.15 357.63 352.39 325.28 473.06 486.17
  27.11 291.18 252.7

**3) Trabalhar com pandas**

* Importar pandas e usar um alias para poder utilizar os seus recursos.

* Carregar como dataframe de pandas csv 05_05_imdb_títulos.csv e mostrar os seus 5 primeiros registos.
* Carregar como dataframe de pandas o csv 05_05_imdb_elenco.csv e mostrar os seus 5 primeiros registos

In [25]:
import pandas as pd 

df_titulos = pd.read_csv('./csv/05_05_imdb_titulos.csv')

df_elenco = pd.read_csv('./csv/05_05_imdb_elenco.csv')

print(f"Os primeiros 5 dados do titulos:")
df_titulos.head(5) # troque pela quantidade de linhas iniciais
print("--"*50)

print(f"Os primeiros 5 dados do elenco")
df_elenco.head(5)


Os primeiros 5 dados do titulos:
----------------------------------------------------------------------------------------------------
Os primeiros 5 dados do elenco


title    year      name   type                character  \
0        Closet Monster  2015.0  Buffy #1  actor                  Buffy 4   
1       Suuri illusioni  1985.0    Homo $  actor                   Guests   
2   Battle of the Sexes  2017.0   $hutter  actor          Bobby Riggs Fan   
3  Secret in Their Eyes  2015.0   $hutter  actor          2002 Dodger Fan   
4            Steve Jobs  2015.0   $hutter  actor  1988 Opera House Patron   

      n  
0  31.0  
1  22.0  
2  10.0  
3   NaN  
4   NaN

* Mostrar o número de registos do dataframe de títulos.
* Mostrar o número de registos do dataframe de elenco.


In [28]:
df_titulos = pd.read_csv('./csv/05_05_imdb_titulos.csv')
df_elenco = pd.read_csv('./csv/05_05_imdb_elenco.csv')

# com shape
num_registro_titulos_shape = df_titulos.shape[0]
# com len
num_registro_elenco_len = len(df_elenco)
print(f"Número de registro do titulos: {num_registro_titulos_shape}")
print(f"Numero de registro do elenco: {num_registro_elenco_len}")

Número de registro do titulos: 230407
Numero de registro do elenco: 2641020


* Mostrar os 5 titulos mais antigas.

In [29]:
df_titulos = pd.read_csv('./csv/05_05_imdb_titulos.csv')

df_titulos_antigos = df_titulos.sort_values(by='year', ascending= True)

df_titulos_antigos.head()

title  year
13229                                          Miss Jerry  1894
103233                                 The Startled Lover  1898
133020     Reproduction of the Corbett and Jeffries Fight  1899
195127  Pierrot's Problem, or How to Make a Fat Wife O...  1900
136487                              Soldiers of the Cross  1900

* Mostrar os filmes que no título contem a palavra “Drácula”. Quantos filmes são?

In [33]:
import pandas as pd 

df_titulos = pd.read_csv('./csv/05_05_imdb_titulos.csv')

palavra_chave = 'Dracula'

df_filmes_dracula = df_titulos[df_titulos['title'].str.contains(palavra_chave, case=False, na=False)]

print(df_filmes_dracula)

total_filmes = len(df_filmes_dracula)
print(f"Quantos filmes do Dracula existe: [{total_filmes}]")



                                  title  year
3903         Bonnie & Clyde vs. Dracula  2008
4851                   House of Dracula  1945
13441                    Batman Dracula  1964
15371   Young-guwa heubhyeolgwi dracula  1992
20794                 Terror of Dracula  2012
...                                 ...   ...
214826                    Dracula's Dog  1978
221137                      Dracula Now  2015
224233     The Satanic Rites of Dracula  1973
228121                   Son of Dracula  1974
229161               Dracula and Stoker  2012

[84 rows x 2 columns]
Quantos filmes do Dracula existe: [84]


* Mostrar os 10 títulos mais comuns (que mais se repetem).

In [34]:
import pandas as pd 

df_titulos = pd.read_csv('./csv/05_05_imdb_titulos.csv')

titulos_mais_comums = df_titulos['title'].value_counts()
titulos_mais_comums.head()

title
Hamlet                  19
Carmen                  16
Macbeth                 15
The Three Musketeers    11
Hero                    11
Name: count, dtype: int64

* Mostrar qual foi o primeiro filme chamado “Romeo and Juliet”.

In [39]:
import pandas as pd 

df_titulos = pd.read_csv('./csv/05_05_imdb_titulos.csv')

buscar_palavra = "Romeo and Juliet"

buscar_palavra_na_tabela = df_titulos[df_titulos['title'].str.contains(buscar_palavra, case=False, na=False)]

ordenar = buscar_palavra_na_tabela.sort_values(by='year', ascending=True)
ordenar.head(1)

title  year
124702  Romeo and Juliet  1916

* Listar todas os filmes que contenham a palavra “Exorcist”, ordenados do mais antigo ao mais recente.

In [40]:
import pandas as pd 

df_titulos = pd.read_csv('./csv/05_05_imdb_titulos.csv')

buscar_palavra = "Exorcist"

filmes = df_titulos[df_titulos['title'].str.contains(buscar_palavra, case=False, na=False)]

ordenar_em_ordem_cres = filmes.sort_values(by='year', ascending=True)

print(f"Titulo buscado [{buscar_palavra}]")
print(ordenar_em_ordem_cres)

Titulo buscado [Exorcist]
                                         title  year
88003                             The Exorcist  1973
49658                  O Exorcista de Mulheres  1974
118920     Satanico Pandemonium: La Sexorcista  1975
140519                Exorcist II: The Heretic  1977
220073                        Kung Fu Exorcist  1978
17375                         The Exorcist III  1990
132451                        Teenage Exorcist  1991
117797                 Exorcist: The Beginning  2004
94189        Dominion: Prequel to the Exorcist  2005
209250  Costa Chica: Confession of an Exorcist  2006
86354                      Exorcist Chronicles  2007
130686                      The Disco Exorcist  2011
57932                      Exorcist Chronicles  2013
69974                           Shark Exorcist  2015
151850                              Exorcistas  2015
51101                            Bad Exorcists  2015
161093                       American Exorcist  2016
60700               

* Mostrar quantos filmes foram feitas no ano 1950.

In [41]:
import pandas as pd 

df_titulos = pd.read_csv('./csv/05_05_imdb_titulos.csv')

# Contar quantos filmes foram feitos no ano de 1950
filmes_no_ano_50 = (df_titulos['year'] == 1950).sum()

print(f"Quantidade de filmes feitos no ano de 1950: {filmes_no_ano_50}")

Quantidade de filmes feitos no ano de 1950: 1081


* Mostrar quantaos filmes foram feitas de 1950 a 1959 (inclusive).

In [43]:
import pandas as pd 

df_titulos = pd.read_csv('./csv/05_05_imdb_titulos.csv')

# filmes entre 1950 e 1959
filmes_entre_50_59 = ((df_titulos['year'] > 1949) & (df_titulos['year'] <= 1959)).sum()
print(f"Quantidade de filmes feitos entre 1950 e 1959: {filmes_entre_50_59}")

Quantidade de filmes feitos entre 1950 e 1959: 12606


* Mostrar todas os papéis que teve a trilogia “The Godfather”, agrupando pelo papel e forneca a informação da quantidade de vezes esse papel apareceu (exemplo: michael corleone aparece nos 3 filmes da triologia).

In [53]:
import pandas as pd 

df_elenco = pd.read_csv('./csv/05_05_imdb_elenco.csv')

# pesquisar por ator
ator = "Al Pacino"

# Filtrar os dados para incluir apenas os filmes da triologia do " The Godfather"
triologia_godfather = df_elenco[df_elenco['title'].str.contains("The GodFather", case=False, na=False)]

# Buscar por "Michael" ou ator
buscar_nome_personagen = triologia_godfather[triologia_godfather['character'].str.contains("Michael Corleone")]
buscar_nome_ator = triologia_godfather[triologia_godfather['name'].str.contains(ator)]

qnt_buscar_nome = buscar_nome_personagen.shape[0]

triologia_godfather.head()
print(buscar_nome_personagen)
print(qnt_buscar_nome)

qnt_nome_ator = buscar_nome_ator.shape[0]
print(f"Ator buscado {ator}, fez {qnt_nome_ator} papeis")

                           title    year       name   type  \
1642816            The Godfather  1972.0  Al Pacino  actor   
1642818  The Godfather: Part III  1990.0  Al Pacino  actor   

                    character    n  
1642816      Michael Corleone  2.0  
1642818  Don Michael Corleone  1.0  
2
Ator buscado Al Pacino, fez 3 papeis


* Mostrar o elenco completo, ordenado pela classificação “n” do filme “Drácula” de 1958.


In [55]:
import pandas as pd 

df_elenco = pd.read_csv('./csv/05_05_imdb_elenco.csv')

# elenco no dracula de 1958

filme = 'dracula'
ano = 1958

# filtrar os dados do filme de dracula de 1958
dracula_1958 = df_elenco[(df_elenco['title'].str.contains(filme, case=False, na=False)) & (df_elenco['year'] == ano)]

# ordenando por por "n"

ordenado_por_n_dracula_1958 = dracula_1958.sort_values(by='n')
ordenado_por_n_dracula_1958

title    year                   name     type  \
1240853  The Return of Dracula  1958.0        Francis Lederer    actor   
485197                 Dracula  1958.0          Peter Cushing    actor   
1242308                Dracula  1958.0        Christopher Lee    actor   
1242307                Dracula  1958.0        Christopher Lee    actor   
822398                 Dracula  1958.0          Michael Gough    actor   
2091208  The Return of Dracula  1958.0          Ray Stricklyn    actor   
2306094  The Return of Dracula  1958.0           John Wengraf    actor   
408463   The Return of Dracula  1958.0            Gage Clarke    actor   
2220986                Dracula  1958.0        John Van Eyssen    actor   
110877   The Return of Dracula  1958.0            Jimmy Baird    actor   
2444220                Dracula  1958.0         Barbara Archer  actress   
1285506                Dracula  1958.0     Charles Lloyd Pack    actor   
1453367                Dracula  1958.0         George Merritt    actor   
2357769                Dracula  1958.0      George Woodbridge    actor   
171732                 Dracula  1958.0          George Benson    actor   
1347640                Dracula  1958.0         Miles Malleson    actor   
148496                 Dracula  1958.0       Geoffrey Bayldon    actor   
423307                 Dracula  1958.0              Paul Cole    actor   
38868    The Return of Dracula  1958.0        Melvin F. Allen    actor   
673736   The Return of Dracula  1958.0        William Fawcett    actor   
746702   The Return of Dracula  1958.0            Dan Gachman    actor   
885191   The Return of Dracula  1958.0        Joseph Hamilton    actor   
1318929  The Return of Dracula  1958.0            Robert Lynn    actor   
1433374  The Return of Dracula  1958.0          John McNamara    actor   
1475047                Dracula  1958.0              Guy Mills    actor   
1513434                Dracula  1958.0  Richard (VIII) Morgan    actor   
1524497                Dracula  1958.0      John (II) Mossman    actor   
1937417  The Return of Dracula  1958.0       Norbert Schiller    actor   
2127813  The Return of Dracula  1958.0         Charles Tannen    actor   

                                      character     n  
1240853  Count Dracula, posing as Bellac Gordal   1.0  
485197                       Doctor Van Helsing   1.0  
1242308                           Count Dracula   2.0  
1242307                                 Dracula   2.0  
822398                                   Arthur   3.0  
2091208                              Tim Hansen   3.0  
2306094                           John Merriman   4.0  
408463                Reverend Doctor Whitfield   6.0  
2220986                                Jonathan   7.0  
110877                          Mickey Mayberry   7.0  
2444220                                    Inga  10.0  
1285506                           Doctor Seward  11.0  
1453367                               Policeman  12.0  
2357769                                Landlord  13.0  
171732                                 Official  14.0  
1347640                              Undertaker  15.0  
148496                                   Porter  16.0  
423307                                      Lad  17.0  
38868                    Mel, the Baggage Clerk   NaN  
673736                   Eddie - Station Master   NaN  
746702                             County Clerk   NaN  
885191          Man Reporting Murder at Station   NaN  
1318929                        Dr. Paul Beecher   NaN  
1433374                        Sheriff Bicknell   NaN  
1475047                            Coach Driver   NaN  
1513434                Coach Driver's Companion   NaN  
1524497                           Hearse Driver   NaN  
1937417                          Bellack Gordal   NaN  
2127813       Mack Bryant, Dept. of Immigration   NaN

* Mostrar quantos papéis teve “Bruce Wayne” como protagonista (Dica: Em Batman de 1989, existe Bruce Wayne e tambem Young Bruce Wayne, que deverão ambos aparecer).

In [57]:
import pandas as pd 

df_elenco = pd.read_csv('./csv/05_05_imdb_elenco.csv')

nome_buscado = "Bruce Wayne"

filtro_nome = df_elenco[df_elenco['character'].str.contains(nome_buscado, case=False, na=False)]

# agora temos todos dados e vamos ver quantos nomes temos 
contar_personagem = filtro_nome['character'].value_counts()

contar_personagem

character
Bruce Wayne                 38
Young Bruce Wayne            6
Bruce Wayne - age 8          1
Bruce Wayne - Age 8          1
Waiter Bruce Wayne Party     1
Bruce Wayne's Girlfriend     1
Name: count, dtype: int64


* Mostrar quantos papéis fez “Robert de Niro” na sua carreira.


In [59]:
import pandas as pd 

df_elenco = pd.read_csv('./csv/05_05_imdb_elenco.csv')

nome_buscado = "Robert de Niro"

ator = df_elenco[df_elenco['name'].str.contains(nome_buscado, case=False, na=False)]

numero_d_vezes = ator.shape[0]

print(f"O/A {nome_buscado} fez {numero_d_vezes} personagen")

O/A Robert de Niro fez 103 personagen


* Listagem de papéis como protagonista (n=1) que teve o ator “Charlton Heston” na década dos 60’s, ordenado  por ano de forma descendente.

In [ ]:
import pandas as pd 

df_elenco = pd.read_csv('./csv/05_05_imdb_elenco.csv')

buscar_nome = "Charlton Heston"

# buscar papel numero 1
filtro_n1 = df_elenco[df_elenco['n'] == 1]

# buscar nome na decada de 60
filtro_ator = df_elenco[(df_elenco['name'].str.contains(buscar_nome, case=False, na=False)) & (df_elenco['year'] >= 1960) & (df_elenco['year'] < 1970) & (df_elenco['n'] == 1)]
ordem_decresent_ator = filtro_ator.sort_values(by='year', ascending=False)

lista_dos_papeis = ordem_decresent_ator[['title', 'character', 'year']]

lista_dos_papeis

title                      character    year
944074                 Number One               Ron 'Cat' Catlan  1969.0
944077         Planet of the Apes                  George Taylor  1968.0
944050               Counterpoint                   Lionel Evans  1967.0
944120                 Will Penny                     Will Penny  1967.0
944066                   Khartoum  Gen. Charles 'Chinese' Gordon  1966.0
944068               Major Dundee      Major Amos Charles Dundee  1965.0
944111               The War Lord                      Chrysagon  1965.0
944085  The Agony and the Ecstasy                   Michelangelo  1965.0
944038          55 Days at Peking                Maj. Matt Lewis  1963.0
944052               Diamond Head         Richard 'King' Howland  1962.0
944103  The Pigeon That Took Rome                       Narrator  1962.0
944101  The Pigeon That Took Rome        Captain Paul MacDougall  1962.0
944102  The Pigeon That Took Rome               Benny the Snatch  1962.0
944054                     El Cid        El Cid Rodrigo de Vivar  1961.0

* Mostrar quantos papéis para atores teve na década 50’s.
* Mostrar quantos papéis para atrizes teve na década 50’s.

In [71]:
import pandas as pd 

df_elenco = pd.read_csv('./csv/05_05_imdb_elenco.csv')

# filtros de atores e atrizes entre o periodo de 1950 e 1959
decada_50 = df_elenco[(df_elenco['year'] >= 1950) & (df_elenco['year'] < 1960)]

atores_dec_50 = decada_50[decada_50['type'] == 'actor']
atores_dec_50_shape = atores_dec_50.shape[0]
print(f"Atores entre o periode de 1950 e 1959: {atores_dec_50_shape}")

#atrizes_decada_50 = decada_50['type'] == 'actress' # isso busca tudo 

atrizes_dec_50 = decada_50[decada_50['type'] == 'actress']
atrizes_dec_50_len = len(atrizes_dec_50)

print(f"Atrizes entre o periode de 1950 e 1959: {atrizes_dec_50_len}")

diferenca_entre_papeis = atores_dec_50_shape - atrizes_dec_50_len

print(f"A diferença entre {diferenca_entre_papeis}")


Atores entre o periode de 1950 e 1959: 153998
Atrizes entre o periode de 1950 e 1959: 10894
A diferença entre 143104
