In [2]:
import numpy as np

In [3]:
lista = np.array([1, 2, 3, 4, 5])

In [4]:
print(lista)

[1 2 3 4 5]


In [6]:
print(np.__version__)

2.2.1


In [7]:
print(type(lista))

<class 'numpy.ndarray'>


In [14]:
lista1 = np.array([1, 2, 3, 4, 5] )

In [15]:
print(lista1)

[1 2 3 4 5]


In [19]:
lista2 = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [20]:
print(lista2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
print(lista2.ndim)

2


In [22]:
lista3 = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[1,2,3], [4,5,6], [7,8,9]]])

In [24]:
print(lista3.ndim)
print(lista3)

3
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
import numpy as np

# criando uma lista de 10 a 100
lista = np.arange(10, 101)
print(lista)

# invertendo a lista
lista2 = lista[::-1]
print(lista2)

# criando um array 3x3 com valores de 0 a 8
lista3 = np.arange(9).reshape(3,3)
print(lista3)

# Criando um array identidade de 6 x 6 
lista4 = np.eye(6)
print(lista4)

# Criando um array 3x3x3 com valores aleatórios
lista5 = np.random.random((3,3,3))
print(lista5)



[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]
[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[[0.11226354 0.75461038 0.03482806]
  [0.78978794 0.94494389 0.78165414]
  [0.76456995 0.84136613 0.19

In [29]:
# Criando 2 arrays com valores ao acasso, A e B, e verificando se são iguais
A = np.random.random((5,5))
B = np.random.random((3,3))
print(A)
print(B)
print("*"*50)

# Validadando se os arrays são iguais
if A.shape != B.shape:
    print(f"Os arrays não são iguais {A.shape} e {B.shape} ")
    # redimensionando o array B para o mesmo tamanho de A
    B = np.resize(B, A.shape)
else: 
    print("Os arrays têm o mesma forma!")
print("-"* 50)
# Metodo 1 : Usando np.array_equal()
print(f"Usando o metodo np.array_equal() : {np.array_equal(A, B)}")
print("*"*50)
# Metodo 2 : Usando np.allclose()
are_equal_allclose = np.allclose(A, B)
print(f"Usando o metodo np.allclose() : {are_equal_allclose}")
print("*"*50)

# metodo 3 : Usando np.array_equiv()
are_equal_equiv = np.array_equiv(A, B)
print(f"Usando o metodo np.array_equiv() : {are_equal_equiv}")
print("*"*50)

# metodo 4 : Usando numpy.all com numpy.equal
sao_todos_iguais =  np.all(np.equal(A, B))
print(f"Usando o metodo np.all(np.equal()) : {sao_todos_iguais}")



[[0.22917575 0.52881066 0.89572445 0.60604942 0.44457652]
 [0.28351664 0.63313064 0.60667854 0.94634754 0.09511655]
 [0.51803215 0.95410558 0.93495363 0.52211439 0.2810154 ]
 [0.26022246 0.6373953  0.27901886 0.74723833 0.45278697]
 [0.58802884 0.30358323 0.31861989 0.96612091 0.39976905]]
[[0.67519701 0.8846515  0.54476748]
 [0.9481444  0.33015961 0.31221349]
 [0.50888413 0.28351852 0.36856365]]
**************************************************
Os arrays não são iguais (5, 5) e (3, 3) 
--------------------------------------------------
Usando o metodo np.array_equal() : False
**************************************************
Usando o metodo np.allclose() : False
**************************************************
Usando o metodo np.array_equiv() : False
**************************************************
Usando o metodo np.all(np.equal()) : False
