# Exercícios Módulo 5. Livrarias especializadas em dados (Soluções)

Considerações a ter em conta:

* Guardar este documento com o seguinte formato para entrega: __M5_05_nome_apelido1_apelido2__
* Fazer os exercícios com as ferramentas vistas nas sessões. 
* Comentar o código
* Utilizar nomes de variáveis apropriados, se vai guardar uma nota, chamar a essa variável nota, não n ou x

**1) Trabalhar com NumPy**

* Importar numpy e usar um alias para poder utilizar os seus recursos 
* Criar um array de elementos (de 10 a 100)
* Inverter o array
* Criar um array 3x3 com valores de 0 a 8 
* Criar um array identidade de 6x6
* Criar um array com valores aleatórios com o formato 3x3x3
* Criar dois arrays, com valores aleatórios, A e B, e verificar se são iguais (há várias opções, investigar)

In [1]:
# Completar o exercício aqui
import numpy as np

* Criar um array de elementos (de 10 a 100)

In [10]:
lista_de_10_100 = np.arange(10,101)
print(f"Lista de 10 a 100: \n{lista_de_10_100}")
print("-"*70)
# reverso * Inverter o array
lista_reversa = lista_de_10_100[::-1]
print(f"Lista de 100 a 10:\n {lista_reversa}")

Lista de 10 a 100: 
[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]
----------------------------------------------------------------------
Lista de 100 a 10:
 [100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10]


* Criar um array 3x3 com valores de 0 a 8 

In [12]:
array_0_a_8 = np.arange(9).reshape(3,3)
print(array_0_a_8)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


* Criar um array identidade de 6x6

In [15]:
array_identidade_6_6 = np.eye(6)
print(array_identidade_6_6)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


* Criar um array com valores aleatórios com o formato 3x3x3

In [18]:
array_valores_aleatoris_3X3X3 = np.random.randint(0, 100, (3, 3, 3))
print(array_valores_aleatoris_3X3X3)

[[[75 84 20]
  [75 40 90]
  [43 35  3]]

 [[14 53 11]
  [81 89 17]
  [12 40 82]]

 [[48 98 17]
  [65 27 28]
  [31  6 45]]]


* Criar dois arrays, com valores aleatórios, A e B, e verificar se são iguais (há várias opções, investigar)

In [41]:
A = np.random.randint(10, 20, (5,3)) # 1
B = np.random.randint(0, 10, (3, 5))

# Vamos ver se os dois tem o mesmo tamanho

if A.shape != B.shape:
    print(f"Os arrays não tem o mesmo tamanho {A.shape} e {B.shape}")
    
    # deixando o iguais
    B = np.resize(B, A.shape)
    print("Depois da parear")
    print(A)
    print(B)
else:
    print("Os arrays têm a mesma forma.")

print("Originais, como foram criados")
print(A)
print(B)

### Utilizando metodos para ver se são iguais
print("--"*50)
# Metodo 1: Usando np.array_equal()
arrai_igual = np.array_equal(A,B)
print(f"Verificando se os arrays são igual utilizando o np.array_equal() : {arrai_igual}")

# Metodo 2 : 
# Metodo 2 : Usando np.allclose()
are_equal_allclose = np.allclose(A, B)
print(f"Usando o metodo np.allclose() : {are_equal_allclose}")
print("*"*50)

# metodo 3 : Usando np.array_equiv()
are_equal_equiv = np.array_equiv(A, B)
print(f"Usando o metodo np.array_equiv() : {are_equal_equiv}")
print("*"*50)

# metodo 4 : Usando numpy.all com numpy.equal
sao_todos_iguais =  np.all(np.equal(A, B))
print(f"Usando o metodo np.all(np.equal()) : {sao_todos_iguais}")

Os arrays não tem o mesmo tamanho (5, 3) e (3, 5)
Depois da parear
[[11 11 15]
 [17 13 14]
 [18 19 17]
 [12 10 16]
 [14 14 16]]
[[8 8 2]
 [0 3 6]
 [0 2 5]
 [5 7 8]
 [4 4 2]]
Originais, como foram criados
[[11 11 15]
 [17 13 14]
 [18 19 17]
 [12 10 16]
 [14 14 16]]
[[8 8 2]
 [0 3 6]
 [0 2 5]
 [5 7 8]
 [4 4 2]]
----------------------------------------------------------------------------------------------------
Verificando se os arrays são igual utilizando o np.array_equal() : False
Usando o metodo np.allclose() : False
**************************************************
Usando o metodo np.array_equiv() : False
**************************************************
Usando o metodo np.all(np.equal()) : False


**2) Seguir com NumPy**

* Criar um array de 100 elementos aleatórios compreendidos entre 1 e 1000 (podem ser números inteiros). 
* Este array irá chamar-se dólares
* Fazer a conversão dos preços em dólares do primeiro array para um segundo array que se vai chamar euros. Devemos utilizar a  seguinte conversão: 
  - 1 USD = 0,874413 EUR
* Mostrar o resultado do array de euros, arredondando a 2 casas decimais.

In [11]:
import numpy as np

# Criar um array de 100 elementos aleatórios compreendidos entre 1 e 1000 (números inteiros)
dolares = np.random.randint(1, 1001, size=100)
print("Array em dólares:")
print(dolares)

# Taxa de conversão de USD para EUR
taxa_conversao = 0.874413

# Fazer a conversão dos preços em dólares para euros
euros = dolares * taxa_conversao
euros = np.round(euros, 2)  # Arredondar a 2 casas decimais

print("\nArray em euros:")
print(euros)

Array em dólares:
[398 801  74 124   3 298 300 299 225 554 823 544 126 197 303 899 702 923
 474 547 619 789 161 248 328 120 336 285 503 330 264 131 531 401   5 195
 528 641 966 447 734 808 891 224 540 641 569 556 538  53 563 866 698 140
 493 749  20 961 297 591 755 441 522 495 485 794  42 636  38 258 531 794
 505 934 432 478 568 224 313 110 484 988 493 242  47  70 710 685 634 316
 801 469  27 523 223 984 217 508 683 255]

Array em euros:
[348.02 700.4   64.71 108.43   2.62 260.58 262.32 261.45 196.74 484.42
 719.64 475.68 110.18 172.26 264.95 786.1  613.84 807.08 414.47 478.3
 541.26 689.91 140.78 216.85 286.81 104.93 293.8  249.21 439.83 288.56
 230.85 114.55 464.31 350.64   4.37 170.51 461.69 560.5  844.68 390.86
 641.82 706.53 779.1  195.87 472.18 560.5  497.54 486.17 470.43  46.34
 492.29 757.24 610.34 122.42 431.09 654.94  17.49 840.31 259.7  516.78
 660.18 385.62 456.44 432.83 424.09 694.28  36.73 556.13  33.23 225.6
 464.31 694.28 441.58 816.7  377.75 417.97 496.67 195.87 273.69

**3) Trabalhar com pandas**

* Importar pandas e usar um alias para poder utilizar os seus recursos.
* Carregar como dataframe de pandas csv 05_05_imdb_títulos.csv e mostrar os seus 5 primeiros registos.
* Carregar como dataframe de pandas o csv 05_05_imdb_elenco.csv e mostrar os seus 5 primeiros registos
* Mostrar o número de registos do dataframe de títulos.
* Mostrar o número de registos do dataframe de elenco.
* Mostrar os 5 titulos mais antigas.
* Mostrar os filmes que no título contem a palavra “Drácula”. Quantos filmes são?
* Mostrar os 10 títulos mais comuns (que mais se repetem).
* Mostrar qual foi o primeiro filme chamado “Romeo and Juliet”.
* Listar todas os filmes que contenham a palavra “Exorcist”, ordenados do mais antigo ao mais recente.
* Mostrar quantos filmes foram feitas no ano 1950.
* Mostrar quantaos filmes foram feitas de 1950 a 1959 (inclusive).
* Mostrar todas os papéis que teve a trilogia “The Godfather”, agrupando pelo papel e forneca a informação da quantidade de vezes esse papel apareceu (exemplo: michael corleone aparece nos 3 filmes da triologia).
* Mostrar o elenco completo, ordenado pela classificação “n” do filme “Drácula” de 1958.
* Mostrar quantos papéis teve “Bruce Wayne” como protagonista (Dica: Em Batman de 1989, existe Bruce Wayne e tambem Young Bruce Wayne, que deverão ambos aparecer).
* Mostrar quantos papéis fez “Robert de Niro” na sua carreira.
* Listagem de papéis como protagonista (n=1) que teve o ator “Charlton Heston” na década dos 60’s, ordenado  por ano de forma descendente.
* Mostrar quantos papéis para atores teve na década 50’s.
* Mostrar quantos papéis para atrizes teve na década 50’s.

In [21]:
# Completar o exercício aqui
import pandas as pd

* Carregar como dataframe de pandas csv 05_05_imdb_títulos.csv e mostrar os seus 5 primeiros registos.

In [23]:
# abrindo um arquivo com pandas
elenco_csv = "csv/05_05_imdb_elenco.csv"
# abrindo o arquivo CSV com pandas
df = pd.read_csv(elenco_csv)

#exibindo as primeiras linhas do DataFrame
df.head(10)

title    year  \
0                                     Closet Monster  2015.0   
1                                    Suuri illusioni  1985.0   
2                                Battle of the Sexes  2017.0   
3                               Secret in Their Eyes  2015.0   
4                                         Steve Jobs  2015.0   
5                             Straight Outta Compton  2015.0   
6                             Straight Outta Compton  2015.0   
7                                     For Thy Love 2  2009.0   
8  Lapis, Ballpen at Diploma, a True to Life Journey  2014.0   
9                                       Desire (III)  2014.0   

                        name   type                               character  \
0                   Buffy #1  actor                                 Buffy 4   
1                     Homo $  actor                                  Guests   
2                    $hutter  actor                         Bobby Riggs Fan   
3                    $hutter  actor                         2002 Dodger Fan   
4                    $hutter  actor                 1988 Opera House Patron   
5                    $hutter  actor                             Club Patron   
6                    $hutter  actor                                 Dopeman   
7               Bee Moe $lim  actor                                  Thug 1   
8  Jori ' Danilo' Jurado Jr.  actor                           Jaime (young)   
9           Syaiful 'Ariffin  actor  Actor Playing Eteocles from 'Antigone'   

      n  
0  31.0  
1  22.0  
2  10.0  
3   NaN  
4   NaN  
5   NaN  
6   NaN  
7   NaN  
8   9.0  
9   NaN



* Carregar como dataframe de pandas o csv 05_05_imdb_elenco.csv e mostrar os seus 5 primeiros registos

In [27]:
titulos_csv = "csv/05_05_imdb_titulos.csv"
df_titulos = pd.read_csv(titulos_csv)
df_titulos.head(10)
df_titulos.tail()

title  year
230402         El lobo negro  1981
230403  Komu na Rusi zhit...  1989
230404              Senotaji  2013
230405     The Leopard Woman  1920
230406    Mio caro assassino  1972

* Mostrar o número de registos do dataframe de títulos.


In [36]:
df_titulos = pd.read_csv(titulos_csv)

num_registro_shape = df_titulos.shape[0]
print(f"Número de registros (usando shape): {num_registro_shape}")

num_registro_len = len(df_titulos)
print(f"Números de registros (usando len): {num_registro_len}")

df_titulos.info()

Número de registros (usando shape): 230407
Números de registros (usando len): 230407
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230407 entries, 0 to 230406
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype 
---  ------  --------------   ----- 
 0   title   230406 non-null  object
 1   year    230407 non-null  int64 
dtypes: int64(1), object(1)
memory usage: 3.5+ MB


* Mostrar o número de registos do dataframe de elenco.

In [35]:
df_elenco = pd.read_csv(elenco_csv)

df_elenco.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2641020 entries, 0 to 2641019
Data columns (total 6 columns):
 #   Column     Dtype  
---  ------     -----  
 0   title      object 
 1   year       float64
 2   name       object 
 3   type       object 
 4   character  object 
 5   n          float64
dtypes: float64(2), object(4)
memory usage: 120.9+ MB


* Mostrar os 5 titulos mais antigas.

In [42]:
df_titulos = pd.read_csv(titulos_csv)

df_titulos_ordenado_por_data = df_titulos.sort_values(by='year', ascending= True)

df_titulos_ordenado_por_data.head()



title  year
13229                                          Miss Jerry  1894
103233                                 The Startled Lover  1898
133020     Reproduction of the Corbett and Jeffries Fight  1899
195127  Pierrot's Problem, or How to Make a Fat Wife O...  1900
136487                              Soldiers of the Cross  1900

* Mostrar os filmes que no título contem a palavra “Drácula”. Quantos filmes são?

In [9]:
import pandas as pd

titulos_csv = "./csv/05_05_imdb_titulos.csv"

df_titulos = pd.read_csv(titulos_csv)

# fizemos a pesquisa no df na coluna de titulos para ver se contein a palavra "TAL"
df_busca_por_dracula = df_titulos[df_titulos['title'].str.contains('Dracula', case=False, na=False )]

# aqui ordenamos por ano em ordem crescente
df_busca_por_dracula_ordenado = df_busca_por_dracula.sort_values(by='year', ascending= True)

# Mostrar os titulos que contem a palavra dracula
print("Titulos que contem a palavra 'Drácula':")
print(df_busca_por_dracula_ordenado)

# Contar quantos titulos são 
df_busca_por_dracula_ordenado = df_busca_por_dracula.shape[0]
print(f"Numéro de titulos que contem a palavra 'Dracula': {df_busca_por_dracula_ordenado}")

Titulos que contem a palavra 'Drácula':
                           title  year
94156                    Dracula  1931
188854        Dracula's Daughter  1936
163326            Son of Dracula  1943
4851            House of Dracula  1945
48770           Blood of Dracula  1957
...                          ...   ...
117907         Dracula A.D. 2015  2015
147755           Cult of Dracula  2016
150603             Dracula's War  2018
194874  Frankenstein vs. Dracula  2018
156968                   Dracula  2019

[84 rows x 2 columns]
Numéro de titulos que contem a palavra 'Dracula': 84


In [33]:


def saber_quantos_titulos__tem(titulo):
    import pandas as pd 
    titulos_csv = "./csv/05_05_imdb_titulos.csv"

    df_titulos = pd.read_csv(titulos_csv)

    # fizemos a pesquisa no df na coluna de titulos para ver se contein a palavra "TAL"
    df_busca_por_titulo = df_titulos[df_titulos['title'].str.contains(titulo, case=False, na=False )]
    # Contar quantos titulos são 
    quantidade_resultado_encontrado = df_busca_por_titulo.shape[0]
    try:
        print(f"Seu palavra de pesquisa -> {titulo} <- corresponde a {quantidade_resultado_encontrado}")
      #  return df_busca_por_titulo
    except ValueError as ve:
        print(ve)
    except Exception as ex:
        print(ex)

def mostrar_os_resultados_encontrados(titulo):
    import pandas as pd 
    titulos_csv = "./csv/05_05_imdb_titulos.csv"

    df_titulos = pd.read_csv(titulos_csv)

    # fizemos a pesquisa no df na coluna de titulos para ver se contein a palavra "TAL"
    df_busca_por_titulo = df_titulos[df_titulos['title'].str.contains(titulo, case=False, na=False )]

    df_busca_por_titulo_ordenado = df_busca_por_titulo.sort_values(by='year', ascending=True)

    print("Titulos e ano do filme:")
    print(df_busca_por_titulo_ordenado)


In [24]:
# quero saber tantas vezes TAL palavra aparece no dataframe
saber_quantos_titulos__tem("Alien") # Troque pela palavra que desejar
    

Seu palavra de pesquisa -> Alien <- corresponde a 217


In [34]:
mostrar_os_resultados_encontrados("Romeo and Juliet") # Troque pela palavra que desejar 

Titulos e ano do filme:
                                           title  year
124702                          Romeo and Juliet  1916
147098                     Romeo and Juliet (II)  1916
82622                           Romeo and Juliet  1936
147308                          Romeo and Juliet  1947
87037                           Romeo and Juliet  1954
196039                          Romeo and Juliet  1966
185337                          Romeo and Juliet  1968
143360  The Secret Sex Lives of Romeo and Juliet  1969
130431           The Tragedy of Romeo and Juliet  1982
171252                A Village Romeo and Juliet  1992
146278                         Tromeo and Juliet  1996
837                  Romeo and Juliet in Yiddish  2010
144796                          Romeo and Juliet  2013
193910             Romeo and Juliet: A Love Song  2013
166553                     Romeo and Juliet (II)  2014
16975                           Romeo and Juliet  2014
192649           George Anton's Romeo and

* Mostrar os 10 títulos mais comuns (que mais se repetem).

In [25]:
import pandas as pd 
titulos_csv = "./csv/05_05_imdb_titulos.csv"

df_titulos = pd.read_csv(titulos_csv)

# Titulos mais comuns
titulos_mais_comuns = df_titulos['title'].value_counts()

print(titulos_mais_comuns)


title
Hamlet                   19
Carmen                   16
Macbeth                  15
The Three Musketeers     11
Hero                     11
                         ..
I Love Budapest           1
Make Pretend              1
The Family Stone          1
Peril of the Plains       1
Chelovek bez pasporta     1
Name: count, Length: 210690, dtype: int64


* Mostrar qual foi o primeiro filme chamado “Romeo and Juliet”.

In [40]:
# Exemplo de uso
romeo = mostrar_os_resultados_encontrados("Romeo and Juliet")

Titulos e ano do filme:
                                           title  year
124702                          Romeo and Juliet  1916
147098                     Romeo and Juliet (II)  1916
82622                           Romeo and Juliet  1936
147308                          Romeo and Juliet  1947
87037                           Romeo and Juliet  1954
196039                          Romeo and Juliet  1966
185337                          Romeo and Juliet  1968
143360  The Secret Sex Lives of Romeo and Juliet  1969
130431           The Tragedy of Romeo and Juliet  1982
171252                A Village Romeo and Juliet  1992
146278                         Tromeo and Juliet  1996
837                  Romeo and Juliet in Yiddish  2010
144796                          Romeo and Juliet  2013
193910             Romeo and Juliet: A Love Song  2013
166553                     Romeo and Juliet (II)  2014
16975                           Romeo and Juliet  2014
192649           George Anton's Romeo and

* Listar todas os filmes que contenham a palavra “Exorcist”, ordenados do mais antigo ao mais recente.

In [41]:
mostrar_os_resultados_encontrados("Exorcist")

Titulos e ano do filme:
                                         title  year
88003                             The Exorcist  1973
49658                  O Exorcista de Mulheres  1974
118920     Satanico Pandemonium: La Sexorcista  1975
140519                Exorcist II: The Heretic  1977
220073                        Kung Fu Exorcist  1978
17375                         The Exorcist III  1990
132451                        Teenage Exorcist  1991
117797                 Exorcist: The Beginning  2004
94189        Dominion: Prequel to the Exorcist  2005
209250  Costa Chica: Confession of an Exorcist  2006
86354                      Exorcist Chronicles  2007
130686                      The Disco Exorcist  2011
57932                      Exorcist Chronicles  2013
69974                           Shark Exorcist  2015
151850                              Exorcistas  2015
51101                            Bad Exorcists  2015
161093                       American Exorcist  2016
60700                 

* Mostrar quantos filmes foram feitas no ano 1950.

In [44]:
# Contar quantos filmes foram feitos no ano 1950
import pandas as pd

# Caminho para o arquivo CSV
titulos_csv = "./csv/05_05_imdb_titulos.csv"

# Carregar o arquivo CSV
df_titulos = pd.read_csv(titulos_csv)

# Contar quantos filmes foram feitos no ano 1950
filmes_anos_50 = (df_titulos['year'] == 1950).sum()
print(f"Quantidade de filmes feitos no ano 1950: {filmes_anos_50}")

Quantidade de filmes feitos no ano 1950: 1081


* Mostrar quantaos filmes foram feitas de 1950 a 1959 (inclusive).

In [48]:
# Contar quantos filmes foram feitos no ano 1950 a 1959
filmes_entre_50_59 = ((df_titulos["year"] > 1949) & (df_titulos['year'] <= 1959)).sum()
print(f"Quantidade de filmes feitos entre 1950 a 1959: {filmes_entre_50_59}")

Quantidade de filmes feitos entre 1950 a 1959: 12606
